### ISSUE TITLE
Color highlighting has a background color in prism.css

### ISSUE THREAD

**Issue by katemenkhaus** [PredixDev/px-code-design#1]
class of .token.entity has a background in prism.css 

This cause reliability issues in theming:

![screen shot 2017-03-02 at 4 33 11 pm](https://cloud.githubusercontent.com/assets/14931112/23533527/2a221b44-ff67-11e6-9d5c-9ffa2e8e77c6.png)

![screen shot 2017-03-02 at 4 37 18 pm](https://cloud.githubusercontent.com/assets/14931112/23533528/2bc12f62-ff67-11e6-8c5f-04582682a8a3.png)

**Comment by randyaskin** [comment]
Fixed in px-sass-doc and px-demo-snippet - change should be picked up by code-design and any other affected repos the next time they are rebuilt.
